services:
  app:
    build: ./app
    expose:
     - "5000"
    volumes:
     - ./app:/var/www/app/
     - ./run.py:/var/www/run.py
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
     - 80:80
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
     - app
  db:
    build: ./db
    expose:
     - "5432" 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Asia/Tokyo"
    volumes:
      - database:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d

volumes:
  database:
    driver: local